### ISSUE TITLE
Inconsistent runes caused by alternate URLs

### ISSUE THREAD

**Issue by aeonofdiscord** [Rotonde/rotonde-client#16]
If a user has some followers following them via a their raw dat:// ID, and others following them via an alias like a hashbase URL, some mutuals will be incorrectly displayed as non-followers (with ~ instead of @).

**Comment by aeonofdiscord** [comment]
I've just noticed fix_port addresses this but I'm unclear whether it's a complete solution.

**Comment by neauoire** [comment]
I don't think it is, but it's a step toward. People need to stop sharing their hash base urls.. Or set it into their dat.json

**Comment by frozenpandaman** [comment]
Is there any way to "merge" or associate these URLs? Don't 100% understand everything about the dat:// protocol, so maybe this nonsensical, but I think I remember someone making a commit which replaced hyperlinks to hashbase URLs (e.g. in the sidebar) with the associated dat:// links. So, is there any way to make it so when someone copy-pastes in a hashbase URL, it looks up the associated dat:// and adds that to the list in `portal.json` instead?

**Comment by aeonofdiscord** [comment]
Actually, yeah, I'll have a bash at this just now.

**Comment by aeonofdiscord** [comment]
Never mind, looks like @cblgh's fix_ports patch already takes care of it.

**Comment by underscorediscovery** [comment]
does it happen automagically though? (so that hashbase urls never exist in portal.json)

**Comment by cblgh** [comment]
ohhhhh oh i just realized we could basically run what fix_port does whenever the user saves.

i the idea late last night but doing too drastic changes after midnight is never really a good idea **\*yawns\***

**Comment by neauoire** [comment]
I believe that this is fixed. I haven't had this issue since the past couple of PRs.

**Comment by aeonofdiscord** [comment]
I'm still seeing this, but I think I have a fix for it

**Comment by aeonofdiscord** [comment]
Okay, I've figured out a fix but it's hugely inefficient and probably overkill for a minor issue like this. Plus, the problem should hopefully resolve itself as people upgrade their clients, so this can probably be closed for now.

**Comment by maxhaesslein** [comment]
I _think_ it's not working for me; I'm on dat://maxhaessle.in/ and rofollow says deam ( dat://6f2b20227b414fa602c5f2ea9ded7d37819f44117c5b338af949279534d79317/ ) is following me; on their dat it says @maxhaesslein so that's correct but on my dat its ~deam so the wrong rune get's displayed.
I'm using [this method](https://cblgh.org/host-on-dat.html) to redirect dat://maxhaessle.in to my real dat ( dat://1c16b383863398cc028a3d18e7ab807b8e8b43f3c7d5a81a698355f830e89d3f/ ) -- so I think it's just a redirect, not a copy of my original dat like hashbase does and maybe that is causing the issue for me.

**Comment by maxhaesslein** [comment]
So I fixed it for me -- [see this commit](https://github.com/maxhaesslein/rotonde-client/commit/316e37e357468d87a2ee9a1378f6ff8a5e955000).

The problem was, that my own dat was saved in `r.portal.data.dat` as the unresolved uri.

I'm not sure about my changes in _portal.js_ though, maybe someone can have a look at it?

**Comment by frozenpandaman** [comment]
This is still an issue for me. Is there anything I need to do to fix it?

I see people who are following me with a **@** on dat://1327ca6d4caf3c4665f5b82d72a5dc716ddf24f58f253e857c5703b9b6a69838/, but when using dat://elifessler.com/ I see only **~** (as no one's following me using that URL).

**Comment by cblgh** [comment]
close per #124,
