### ISSUE TITLE
mention system for rotonde

### ISSUE THREAD

**Issue by goldbuick** [Rotonde/rotonde-client#46]
Is anyone working on a way to know if you're mentioned by someone who you don't follow?

**Comment by neauoire** [comment]
I think a few people are looking into building crawlers. I'm hoping that this will be built as a sort sort of service/rotonde app. I'm excited to see how this gets implemented!

**Comment by deamme** [comment]
You can use dat://rotosearch-aeon.hashbase.io/ and if you want to see who follows you then you can use dat://rofollow-deam.hashbase.io/.

**Comment by neauoire** [comment]
I think we should ask Aeon if they'd like to have the rotolist on the github organization. I would love to poke around and improve it.

**Comment by aeonofdiscord** [comment]
Hey, that sounds cool, sign me up.

**Comment by neauoire** [comment]
In exchange, you'll have to pick an avatar for you GitHub account.

**Comment by aeonofdiscord** [comment]
you drive a hard bargain

**Comment by karloscarweber** [comment]
I have an opinion on this, but also lots of questions. 

So I think it's a feature that you can't be mentioned by someone that you don't follow. With all of the harassment going on with Twitter, making it impossible to be harassed is great.

I'm working on a rotonde repeater that will probably include a crawler for mentions or direct messages. I was thinking that when using a crawler you can opt-in to allowing mentions from people you follow, or people in your direct network, for example, everyone that people you follow follow.

So would the crawler let anyone mention you or have restrictions?

I'm building the repeater because I'm also working on an iOS client, but there is zero code for dat on an iOS device at the moment, and your portal would just drop off the network when you're not using it.

**Comment by goldbuick** [comment]
@karloscarweber agree, absolutely mentions should be optional
being mindful of potential harassment is good way to look at things
I'm curious how the iOS stuff works, I'm a mobile dev currently working in react native land

**Comment by sno** [comment]
i'm so sorry i can't recall who originally came up with this, but there was talk of potentially having a bot follow everyone (or upon request) to track mentions and alert people via whisper when their name is mentioned by someone they don't follow. could be overkill but i really like it as a way to opt into a more open system.

**Comment by cblgh** [comment]
@sno I made a bot that, when followed, will whisper you mentions! See [my portal](dat://7f2ef715c36b6cd226102192ba220c73384c32e4beb49601fb3f5bba4719e0c5/) for an example.

Its name is @mentions and you may follow at dat://acf76768f02665825ccf7e205268833e096fc232a8cb933c0c12ee03bdd25ccd

(Code [here](https://github.com/cblgh/rotonde-mentions/blob/master/bot.js), for the curious)

Let me know what breaks!

(I'll integrate this into a client-side service module soon:)

**Comment by neauoire** [comment]
At this point I think we need network wide mentions.

**Comment by neauoire** [comment]
We'll make a new issue when we start to look into network-wise mentions.
